### ISSUE TITLE
The IP provided in the description isn't working.

### ISSUE THREAD

**Issue by mananyadav** [abhishekg785/InfoGami#3]
I can't access the website using the IP address given in the description. I think you've taken the server down right? The address - [InfoGami](http://107.170.48.240/)

**Comment by abhishekg785** [comment]
Yes @mananyadav  Thanks for pointing out. The server is down at the moment and i will try to live it ASAP.
Thanks!

**Comment by mananyadav** [comment]
Cool @abhishekg785 ! Look forward to the site.
